### PR TITLE
Add SECURITY.md

### PR DESCRIPTION
**Pull request by jpkrohling**
Follow-up from open-telemetry/opentelemetry-specification#990

﻿Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

### CODE REVIEW

**Review by yurishkuro — APPROVED** [review]

**Comment by bogdandrutu** [comment]
Wait for me to enable CLA

**Comment by yurishkuro** [comment]
* Is there some documentation about the significance of dot-github repository?
* Can we add some README & description to this repository?

**Comment by jpkrohling** [comment]
There's some info in the issue that was created requesting this repo here: open-telemetry/community#544. More specifically, this doc page: https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/creating-a-default-community-health-file

> You can add default community health files to the root of a public repository called .github that is owned by an organization or user account.

**Comment by bogdandrutu** [comment]
Done, easycla is enabled.

**Pull request merged**
